name: "<gradient:#15FF00:#00FFFB>持久挖掘"
max_level: 3
anvil_cost: 2
enchanting_table:
  enabled: true
  chance: 0.01
  min_cost: 30
  max_cost: 30
villager_trades:
  enabled: false
  chance: 0.01
  treasure: true
applicable_items: TOOLS
trigger: BLOCK_BREAK
target: SELF
cooldown: 1000
particle:
  type: small_gust
  count: 5
  spread: 0.3
  speed: 0.5
  location: SELF
actions:
  continuous:
    type: potion_effect
    effect: haste
    duration:
      base: 20
      per_level: 20
    amplifier:
      base: 0
      per_level: 1
    particles: false
    icon: false