name: "<gradient:#FFC800:#95FF00>矮人工程师"

# 附魔描述，显示在附魔查询页面的lore中，同时支持Bukkit颜色代码和MiniMessage格式标签
# Enchantment description shown in the enchant browser lore. Supports Bukkit color codes and MiniMessage tags.
description:
  - "&f穿戴后体积-55%，方块交互距离+1.5格"
  - "&f作为代价，你变得脆弱，最大生命-70%"
  - "&b冷却：1秒"
  - "&7可用于：&e头盔"
  - "&d最高等级：1"
  - "&c此附魔超载提升等级无任何收益"
  - "&4冲突附魔："
  - "&4保护、火焰保护、爆炸保护、弹射物保护"
max_level: 1
anvil_cost: 2
enchanting_table:
  enabled: true
  chance: 0.01
  min_cost: 30
  max_cost: 30
villager_trades:
  enabled: false
  chance: 0.01
  treasure: true
applicable_items: HELMETS
trigger: PASSIVE
target: SELF
cooldown: 1000
conflicts:
  - minecraft:protection
  - minecraft:fire_protection
  - minecraft:blast_protection
  - minecraft:projectile_protection
actions:
  small:
    type: attribute_modifier
    attribute: "SCALE"
    amount:
      base: -0.55
      per_level: 0
    operation: "MULTIPLY_SCALAR_1"
    key: "engineering"
    conditions:
      equipped: true
  longhand:
    type: attribute_modifier
    attribute: "BLOCK_INTERACTION_RANGE"
    amount:
      base: 1.5
      per_level: 0
    operation: "ADD_NUMBER"
    key: "engineering"
    conditions:
      equipped: true
  weak:
    type: attribute_modifier
    attribute: "MAX_HEALTH"
    amount:
      base: -0.7
      per_level: 0
    operation: "MULTIPLY_SCALAR_1"
    key: "engineering"
    conditions:
      equipped: true
