name: "<gradient:#AB0000:#FF4800>致残"

# 附魔描述，显示在附魔查询页面的lore中，同时支持Bukkit颜色代码和MiniMessage格式标签
# Enchantment description shown in the enchant browser lore. Supports Bukkit color codes and MiniMessage tags.
description:
  - "&f射击命中目标使其迟缓一段时间"
  - "&b冷却：0秒"
  - "&7可用于：&e弓、十字弩"
  - "&d未超载最高等级：3"
  - "&7提升等级时："
  - "&a提高迟缓等级和持续时间"
  - "&4冲突附魔：易爆"
max_level: 3
anvil_cost: 2
enchanting_table:
  enabled: true
  chance: 0.01
  min_cost: 30
  max_cost: 30
villager_trades:
  enabled: false
  chance: 0.01
  treasure: true
applicable_items: RANGED
trigger: PROJECTILE_HIT
target: ALL_ENTITIES
cooldown: 0
conflicts:
  - meowsenchants:explosive
sound:
  type: entity.player.attack.strong
  volume: 1.0
  pitch: 1.0
particle:
  type: dust_pillar
  count: 20
  spread: 0.6
  speed: 0.01
  location: TARGET
  data:
    material: "minecraft:black_glazed_terracotta"
actions:
  slow:
    type: potion_effect
    effect: slowness
    duration:
      base: 40
      per_level: 40
    amplifier:
      base: 1
      per_level: 1
    particles: false
    icon: false
