name: "<gradient:#00FFFF:#8FCEFF>冰霜刃"

# 附魔描述，显示在附魔查询页面的lore中，同时支持Bukkit颜色代码和MiniMessage格式标签
# Enchantment description shown in the enchant browser lore. Supports Bukkit color codes and MiniMessage tags.
description:
  - "&f攻击造成目标迟缓和挖掘疲劳"
  - "&b冷却：4秒"
  - "&7可用于：&e剑、长矛、斧头"
  - "&d未超载最高等级：3"
  - "&7提升等级时："
  - "&a提升效果等级和持续时间"
  - "&4冲突附魔：流血刃"
max_level: 3
anvil_cost: 2
enchanting_table:
  enabled: true
  chance: 0.01
  min_cost: 30
  max_cost: 30
villager_trades:
  enabled: false
  chance: 0.01
  treasure: true
applicable_items: SHARP_WEAPON
trigger: ATTACK_ENTITY
target: ALL_ENTITIES
cooldown: 4000
conflicts:
  - meowsenchants:bleed
sound:
  type: entity.player.hurt_freeze
  volume: 1.0
  pitch: 0.5
particle:
  type: falling_dust
  count: 15
  spread: 0.5
  speed: 0.01
  location: TARGET
  data:
    material: "minecraft:snow_block"
actions:
  freeze:
    type: potion_effect
    effect: slowness
    duration:
      base: 40
      per_level: 40
    amplifier:
      base: 0
      per_level: 1
    particles: false
    icon: false
  fatigue:
    type: potion_effect
    effect: mining_fatigue
    duration:
      base: 40
      per_level: 40
    amplifier:
      base: 0
      per_level: 1
    particles: false
    icon: false
